Bump Ruby version to 2.6.6
Followup to commit 79428ba36b3a484852af6b43a7b27aa88ddb6c8c.

This should fix the following error when running `docker-compose up`:

```
Your Ruby version is 2.6.5, but your Gemfile specified 2.6.6
The command '/bin/sh -c bundle install --jobs 4' returned a non-zero code: 18
ERROR: Service 'web' failed to build
```